name: outfit_battle
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  material_search: ^0.2.8
  flutter_advanced_networkimage: any
  flutter:
    sdk: flutter
  flutter_svg: ^0.10.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.18.0
  image_picker: ^0.4.12+1
  image_cropper: ^0.0.9
  firebase_auth: ^0.6.6
  google_sign_in: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Swords
      fonts:
        - asset: fonts/Swords.ttf
    - family: Coin
      fonts:
        - asset: fonts/Coin.ttf
    - family: Amatic
      fonts:
        - asset: fonts/AmaticSCBold.ttf
    - family: Josefin
      fonts:
        - asset: fonts/JosefinSansRegular.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/svgs/x-button.svg
   - assets/svgs/slingshot.svg
   - assets/svgs/rings.svg
   - assets/svgs/balloons.svg
   - assets/svgs/scooter.svg
   - assets/svgs/spinner.svg
   - assets/svgs/rocket.svg
   - assets/svgs/coin.svg
   - assets/svgs/podium.svg
   - assets/svgs/train.svg
   - assets/svgs/gamepad.svg
   - assets/svgs/sword.svg
   - assets/svgs/confetti.svg
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
